### ISSUE TITLE
Renaming `ecdsa::{SigningKey, VerifyKey}`

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/signatures#196]
Presently the signing and verification key types are named `SigningKey` and `VerifyKey`. These are a bit inconsistent with each other grammatically. Per a [Twitter straw poll](https://twitter.com/bascule/status/1329444791428521988), in particular people seem to dislike the current names.

Some potential alternatives:

- `ecdsa::{SignKey, VerifyKey}`
- `ecdsa::{SigningKey, VerifyingKey}`
- `ecdsa::key::{Sign, Verify}`

**Comment by newpavlov** [comment]
I think having "key" in the names is important for clarity. How about `SigningKey` and `VerificationKey`? Another good alternative is `PrivateKey` and `PublicKey`, it's a bit shorter and easy to understand.

**Comment by tarcieri** [comment]
> `SigningKey` and `VerificationKey`

`VerificationKey` in particular seems excessively long. I'd prefer `VerifyingKey`.

> `PrivateKey` and `PublicKey`

In general I prefer `SecretKey` to `PrivateKey` as otherwise both key types start with "p" which makes them easier to confuse (also the former naturally lends itself to `sk` and `pk` as short variable names)

But also, see discussion here on Twitter about why using `PublicKey` for verification keys is potentially confusing/misleading:

https://twitter.com/hdevalence/status/1329459841148981248

**Comment by fjarri** [comment]
My choice would be `SigningKey` and `VerifyingKey`. `SignKey`/`VerifyKey` and `Sign`/`Verify`, being verbs, sound like method names that are supposed to do something.

**Comment by newpavlov** [comment]
>I'd prefer VerifyingKey

I can't say exactly why, but to me it sounds a bit wrong. It's just a personal impression, so not that important.

>In general I prefer SecretKey to PrivateKey

Public/private key is a traditional name widely used in literature, so I think `SecretKey` will be a bit more confusing. For variable names I usually use `pubkey`/`privkey`, which is not too short, but has a disadvantage of having different lengths.

As for the linked discussion, it looks like a relatively niche application of digital signatures. In my opinion in an overwhelming amount of cases verification case are public.

**Comment by tarcieri** [comment]
> Public/private key is a traditional naming widely used in literature, so I think SecretKey will be a bit more confusing.

In my experience `SecretKey` is pretty common in cryptographic API design.

The `elliptic-curve` crate already defines `PublicKey` and `SecretKey` types. In addition to everything else, I think it'd be pretty confusing if there were both `elliptic_curve::{SecretKey, PublicKey}` and `ecdsa::{SecretKey, PublicKey}`.

**Comment by fjarri** [comment]
To be honest, I must admit I do not completely understand why there are `Signing/VerifyKey` structs in the first place, and not just implementations of `Signer`/`Verifier` for `Secret/PublicKey`.

**Comment by tarcieri** [comment]
@fjarri since `SecretKey` and `PublicKey` are defined in the `elliptic-curve` crate, the `ecdsa` trait can't add trait impls to them.

However, it'd be good to migrate the types in the `ecdsa` crate to be simple newtypes of `elliptic_curve::{SecretKey, PublicKey}`. I was planning on doing that before the next release.

**Comment by tarcieri** [comment]
Renamed `VerifyKey` to `VerifyingKey` in #200
