### ISSUE TITLE
Question: Generating JWK tokens from NistP256 SigningKeys

### ISSUE THREAD

**Issue by markuskobler** [RustCrypto/signatures#221]
Not sure if this is a question for [signatures](https://github.com/RustCrypto/signatures) or [elliptic-curves](https://github.com/RustCrypto/elliptic-curves) but I'm trying to generate a [JWK token ](https://tools.ietf.org/html/rfc7518#section-6.2) from a `SigningKey<NistP256>`

Unfortunately it needs access to the `"x" (X Coordinate)` and `"y" (Y Coordinate)` Parameters from the `AffinePoint`. Is this even possible currently?

**Comment by tarcieri** [comment]
Something like this should work:

```rust
let (x, y) = p256::EncodedPoint::from(&affine_point).to_untagged_bytes().unwrap().split_at(32);
```

We generally try to prevent raw coordinate access except for cases which truly need it.

This appears to be one (although JWK could win an award for the most overly verbose way to express an ECC key).

I think the best long-term solution is to add JWK support to the `elliptic-curve` crate and provide a generic implementation for `elliptic_curve::PublicKey<C>`.

**Comment by markuskobler** [comment]
Amazing thank you! Could not agree more about how much of a pain working with JWK/JWS has been.

**Comment by tarcieri** [comment]
FYI, native JWK support was added to the `elliptic-curve` crate in https://github.com/RustCrypto/traits/pull/483

I'll get it wired up for the `p256` and `p384` crates soon.
