### ISSUE TITLE
Secp256k1 is computing wrong signatures?

### ISSUE THREAD

**Issue by TheReturnOfJan** [RustCrypto/signatures#235]
<strike>Hello,

I have been using this library to generate Secp256k1 signatures.
When I started writing a JavaScript client to the system I was building, I noticed that the signatures generated in this library and the ones in JS are different.
I then tried comparing this implementation with a [different](https://github.com/paritytech/libsecp256k1) Rust implementation, and the signatures are also off (the other lib agrees with JS).
I wrote a test demonstrating this: https://github.com/TheReturnOfJan/rust-crypto-bug/blob/master/tests/test.rs

Could this be an issue with how the field elements are serialized? Or is it possible that there is a bug in the ecdsa implementation? </strike>

Ok so I tried to recover the sig generated by the other lib with this lib, and I get the same results. I guess the different sigs have something to do with how the k parameter is generated? Anyway, apologies for spamming the issues with this, will close this.

**Comment by tarcieri** [comment]
For Ethereum-style recoverable signatures, the `k256` crate uses RFC6979 deterministic signatures in conjunction with HMAC-DRBG-Keccak256 (or more specifically, the generic implementation in the `ecdsa` crate uses the same digest function used for message hashing as it uses for RFC6979)

My understanding is some other libraries use HMAC-DRBG-SHA256, but then use Keccak256 for message hashing. The generic implementation of the `ecdsa` crate makes it a bit tricky to mix-and-match hash functions like that (and separately it seems a bit silly to do so, but...)

This means they'll compute a different signature (i.e. a different ECDSA `k` value), but the signatures should still verify under the corresponding public key.

If you really want to match the signature exactly, it's possible to do by using `ecdsa::rfc6979::generate_k` and `ecdsa::hazmat::SignPrimitive` directly. But unless your goal is to match some specific test vectors, a slightly different derivation of `k` shouldn't matter.

**Comment by TheReturnOfJan** [comment]
I see. Thank you for the explanation.

**Comment by tarcieri** [comment]
Note: fixed in #633
