### ISSUE TITLE
No SigningKey in Root or the trait bound is not satisfied

### ISSUE THREAD

**Issue by noahsalvadordenjo** [RustCrypto/signatures#274]
When the programm uses  in ```Cargo.toml```  ```ecdsa = "0.10.2"```

```use ecdsa::{SigningKey, Signature, VerifyingKey};``` resolves in
```
unresolved imports `ecdsa::SigningKey`, `ecdsa::VerifyingKey`

no `SigningKey` in the root
```
When Add ```k256 = "0.7.2"``` to ```Cargo.toml``` does resolves in build errors 
```
the trait bound `Secp256k1: CheckSignatureBytes` is not satisfied
   --> /home/noone/.cargo/registry/src/github.com-1ecc6299db9ec823/k256-0.7.2/src/ecdsa/recoverable.rs:253:26
    |
253 | impl From<Signature> for super::Signature {
    |                          ^^^^^^^^^^^^^^^^ the trait `CheckSignatureBytes` is not implemented for `Secp256k1`
    | 
   ::: /home/noone/.cargo/registry/src/github.com-1ecc6299db9ec823/ecdsa-0.10.2/src/lib.rs:138:33
    |
138 | pub struct Signature<C: Curve + CheckSignatureBytes>
    |                                 ------------------- required by this bound in `ecdsa::Signature`

error[E0277]: the trait bound `Secp256k1: CheckSignatureBytes` is not satisfied
   --> /home/noone/.cargo/registry/src/github.com-1ecc6299db9ec823/k256-0.7.2/src/ecdsa/recoverable.rs:80:27
    |
80  |     pub fn new(signature: &super::Signature, recovery_id: Id) -> Result<Self, Error> {
    |                           ^^^^^^^^^^^^^^^^^ the trait `CheckSignatureBytes` is not implemented for `Secp256k1`
    | 
   ::: /home/noone/.cargo/registry/src/github.com-1ecc6299db9ec823/ecdsa-0.10.2/src/lib.rs:138:33
    |
138 | pub struct Signature<C: Curve + CheckSignatureBytes>
    |                                 ------------------- required by this bound in `ecdsa::Signature`

error[E0277]: the trait bound `Secp256k1: CheckSignatureBytes` is not satisfied
   --> /home/noone/.cargo/registry/src/github.com-1ecc6299db9ec823/k256-0.7.2/src/ecdsa/recoverable.rs:254:32
    |
254 |     fn from(sig: Signature) -> Self {
    |                                ^^^^ the trait `CheckSignatureBytes` is not implemented for `Secp256k1`
    | 
   ::: /home/noone/.cargo/registry/src/github.com-1ecc6299db9ec823/ecdsa-0.10.2/src/lib.rs:138:33
    |
138 | pub struct Signature<C: Curve + CheckSignatureBytes>
    |                                 ------------------- required by this bound in `ecdsa::Signature`

error: aborting due to 3 previous errors
````

**Comment by tarcieri** [comment]
> When the programm uses in Cargo.toml ecdsa = "0.10.2"
>
> no `SigningKey` in the root
>
> When Add k256 = "0.7.2" to Cargo.toml does resolves in build errors

The `ecdsa` crate isn't useful on its own. It needs to be paired with a crate like `k256` which provides a concrete implementation of an elliptic curve.

Also, if you look at the docs for `SigningKey`:

https://docs.rs/ecdsa/0.10.2/ecdsa/sign/struct.SigningKey.html

You'll see this:

"This is supported on crate feature **sign** only."

This means you need to supply a `feature = ["sign"]` argument when you import Cargo.toml, or rather something does. It works with `k256` because `k256` is activating this feature.

> the trait bound `Secp256k1: CheckSignatureBytes` is not satisfied

This is a somewhat annoying feature gating issue which was just fixed upstream, but will only be released in the next version:

https://github.com/RustCrypto/elliptic-curves/pull/324

You need to enable the `ecdsa` feature of `k256` (which it sounds like you're probably doing already) along with either the `sha256` or `keccak256` features.

**Comment by noahsalvadordenjo** [comment]
Here's my updated ````cargo.toml```

```
[dependencies]
actix-web = "3"
ecdsa = { version = "0.10.2", features = ["sign"] }
k256 = "0.7.2"
```
Does this still resolve into 
```

```
error[E0432]: unresolved import `ecdsa::VerifyingKey`
 --> src/main.rs:3:36
  |
3 | use ecdsa::{SigningKey, Signature, VerifyingKey};
  |                                    ^^^^^^^^^^^^ no `VerifyingKey` in the root

error[E0425]: cannot find value `OsRng` in this scope
 --> src/main.rs:7:47
  |
7 |     let signing_key = SigningKey::random(&mut OsRng); // Serialize with `::to_bytes()`
  |                                               ^^^^^ not found in this scope

error[E0107]: missing generics for struct `ecdsa::Signature`
   --> src/main.rs:14:20
    |
14  |     let signature: Signature = signing_key.sign(message);
    |                    ^^^^^^^^^ expected 1 type argument
    |
note: struct defined here, with 1 type parameter: `C`
   --> /home/noone/.cargo/registry/src/github.com-1ecc6299db9ec823/ecdsa-0.10.2/src/lib.rs:138:12
    |
138 | pub struct Signature<C: Curve + CheckSignatureBytes>
    |            ^^^^^^^^^ -
help: use angle brackets to add missing type argument
    |
14  |     let signature: Signature<C> = signing_key.sign(message);
    |                             ^^^

error[E0277]: `SigningKey<_>` doesn't implement `Debug`
 --> src/main.rs:8:34
  |
8 |     println!("signing key {:?}", signing_key);
  |                                  ^^^^^^^^^^^ `SigningKey<_>` cannot be formatted using `{:?}` because it doesn't implement `Debug`
  |
  = help: the trait `Debug` is not implemented for `SigningKey<_>`
  = note: required by `std::fmt::Debug::fmt`
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sign` found for struct `SigningKey<_>` in the current scope
  --> src/main.rs:14:44
   |
14 |     let signature: Signature = signing_key.sign(message);
   |                                            ^^^^ method not found in `SigningKey<_>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
3  | use crate::ecdsa::signature::Signer;
   |

error: aborting due to 5 previous errors
```

**Comment by tarcieri** [comment]
Try this in your `Cargo.toml`:

```toml
[dependencies]
actix-web = "3"
k256 = { version = "0.7.2", features = ["ecdsa", "sha256"] }
```

(you shouldn't need to supply `ecdsa` specifically. It's used by `k256`)
