### ISSUE TITLE
Store signing_keys

### ISSUE THREAD

**Issue by noahsalvadordenjo** [RustCrypto/signatures#277]
Is anyway to store signing_keys in a file or in a keyvalue db?
Is possible to use a different random in ```SigningKey::random()```?

**Comment by noahsalvadordenjo** [comment]
Coudl use ```hex::encode()``` on the ```FieldBytes```

**Comment by tarcieri** [comment]
I can't speak to or recommend storing signing keys in a general purpose database.

However, that said, the main serialization format supported by the `ecdsa` crate is PKCS#8 with optional PEM encoding.

The main documentation for this is in the `elliptic-curve` crate:

https://docs.rs/elliptic-curve/0.9.6/elliptic_curve/struct.SecretKey.html#parsing-pkcs8-keys

However, when the `pkcs8` feature of the `ecdsa` crate is enabled, the same traits are available on `ecdsa::SigningKey`:

https://docs.rs/ecdsa/0.10.2/ecdsa/sign/struct.SigningKey.html#impl-FromPrivateKey
