### ISSUE TITLE
SHA3_256 Digest Hashing Support

### ISSUE THREAD

**Issue by MarshallBelles** [RustCrypto/signatures#367]
Hello! 👋 

what would be required for SHA3 hashing support for hazmat::DigestPrimitive?

**Comment by tarcieri** [comment]
`DigestPrimitive` effectively represents a default digest to use, and historically for ECDSA that's been the SHA-2 family.

However, you can use whatever digest you'd like via the [`DigestSigner`](https://docs.rs/signature/1.3.1/signature/trait.DigestSigner.html) trait.

**Comment by MarshallBelles** [comment]
Perfect! Thank you!
