### ISSUE TITLE
EncodePrivateKey for SigningKey

### ISSUE THREAD

**Issue by haraldh** [RustCrypto/signatures#519]
Is there any reason `SigningKey` does not implement `EncodePrivateKey` but only `DecodePrivateKey`?

**Comment by tarcieri** [comment]
Which crate are you referring to?

**Comment by haraldh** [comment]
p384
https://github.com/RustCrypto/elliptic-curves/tree/master/p384

**Comment by bstrie** [comment]
This is referring to [`p384::ecdsa::SigningKey`](https://docs.rs/p384/0.11.2/p384/ecdsa/type.SigningKey.html), which is a typedef for [`ecdsa::SigningKey`](https://docs.rs/ecdsa/0.14.4/ecdsa/struct.SigningKey.html), which doesn't implement `EncodePrivateKey`.

Currently we have a workaround for this: https://github.com/enarx/enarx/blob/f3348b07e87dfcebffe7dd1100dd6e76946918ef/src/cli/key/sev/create.rs#L29-L31
