### ISSUE TITLE
signature v1.0

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/signatures#55]
As you wrote in #32 the main motivation for releasing `signature v1.0` is to enable use of it for dalek crates. But IIUC dalek developers haven't confirmed that they intend to depend on `signature` and I though a better approach will be to use `ed25519` crate as a wrapper around `ed25519-dalek` to implement `signature` traits. This would allow `dalek`developers to be independent from our work on `signature` API and we will have more freedom to experiment with it.

As for transferring `signature` to the traits repo, we should certainly do it, but I think it will be better to postpone it until beginning of the next year (hopefully I will have more time to work on this project at that time).

**Comment by tarcieri** [comment]
>  IIUC dalek developers haven't confirmed that they intend to depend on signature

@isislovecruft is potentially open to it, see:

https://github.com/dalek-cryptography/ed25519-dalek/issues/80

I also have an open PR for it:

https://github.com/dalek-cryptography/ed25519-dalek/pull/102

>  I though a better approach will be to use `ed25519` crate as a wrapper around ed25519-dalek to implement signature traits.

That's pretty much how `signatory-dalek` works today:

https://github.com/tendermint/signatory/tree/develop/signatory-dalek

But "wrapper crates" are a pain to maintain as opposed to integrating the traits natively. We experienced that quite a bit in Signatory, and ended up folding the "wrapper crates" into the `yubihsm` and `ledger-tendermint` crates, which made things quite a bit nicer and easier to maintain, IMO.

**Comment by newpavlov** [comment]
Ok, let's wait for a response to your PR then.

**Comment by tarcieri** [comment]
Sounds good (also I should probably finish it!)

**Comment by tarcieri** [comment]
I've moved the `signature` crate over to `RustCrypto/traits`:

https://github.com/RustCrypto/traits/tree/master/signature

...and opened a 2-week final comment period prior to shipping a 1.0:

https://github.com/RustCrypto/traits/issues/78

I'm trying to direct any remaining final comments to that issue, so I'll close this one.
