### ISSUE TITLE
ecdsa: Why are (Decode|Encode)(Private|Public)Key trait implementations gated behind `pem`?

### ISSUE THREAD

**Issue by turbocool3r** [RustCrypto/signatures#721]
This seems strange since there is the `der` feature. Maybe it would make sense to change it to `der`? I could submit a PR if this is ok.

**Comment by tarcieri** [comment]
The `der` feature alone is only intended to support the DER encoding of ECDSA signatures, i.e. `ecdsa::der::Signature`.

The `DecodePrivateKey` and `DecodePublicKey` impls on `SigningKey` and `VerifyingKey` respectively are gated behind `pkcs8`, not `pem`.

The `EncodePublicKey`/`EncodePrivateKey` impls could probably be moved to being gated under `alloc`+`pkcs8`, potentially in a non-breaking manner. I would agree it doesn't make sense to have those gated under `pem`.
