### ISSUE TITLE
Want to contribute RSA signature

### ISSUE THREAD

**Issue by Irene-123** [RustCrypto/signatures#735]
I'm a beginner & contribute around GitHub in small portions, I create algorithms, like [ciphers in rust](https://github.com/Irene-123/Ciphers-in-Rust) I tried a few in my repo. 
I was hoping to contribute the RSA signature, as I noticed we don't have one, but I'm not sure if someone is already working on it, if yes, I can jump in to learn & start my journey here to contribute. 

Thanks!

**Comment by tarcieri** [comment]
We actually implement RSA signatures in a separate repo: https://github.com/rustcrypto/rsa

However, if you're still interested in contributing an RSA signature implementation, we do have an open issue for the RSA PSS-R signature algorithm: https://github.com/RustCrypto/RSA/issues/231
