### ISSUE TITLE
Serialize for SigningKey

### ISSUE THREAD

**Issue by simpsoneric** [RustCrypto/signatures#818]
Question: is there a reason serde Serialize and Deserialize is not implemented for the ecdsa SigningKey type?  

I see implementations for the VerifyingKey and the Signature, but not the SigningKey type.

**Comment by tarcieri** [comment]
I've generally avoided adding `serde` impls for secret key types, though I can't say we've been 100% consistent with that across the entire project. It's been something of an unstated policy at least with the `elliptic-curve` crates.

Serde serializers are implicit, and using them to serialize secret keys adds an exfiltration path for secret key data which is very hard to audit for.

Many people are less paranoid about secret key data are very eager to make it really easy to serialize secret keys and send them over the network, and maybe it would make sense to add `Serialize` impls, but the idea is somewhat bothersome to me.

Perhaps we should adopt an official documented policy if the decision is deliberately to avoid `Serialize` impls.

**Comment by simpsoneric** [comment]
> I've generally avoided adding serde impls for secret key types, though I can't say we've been 100% consistent with that across the entire project. It's been something of an unstated policy at least with the elliptic-curve crates.

That is a very reasonable approach.  Although I agree, seeing a couple of the secret types having serde impls was confusing.

> Many people are less paranoid about secret key data are very eager to make it really easy to serialize secret keys and send them over the network,

One part I've struggled with here is the need to persist keys to another storage medium.

> Serde serializers are implicit, and using them to serialize secret keys adds an exfiltration path for secret key data which is very hard to audit for.

I've also ended up creating an explicit type that wraps any secret material that gets serialized.  It makes it easy to audit where the secret data is serialized, but I do have a somewhat clumsy feeling wrapper.   Maybe that needs to be improved instead.

Now that you bring up the "implicit serialization" tradeoff, I think you're right about it being a more auditable approach to have a distinct type instead.

> Perhaps we should adopt an official documented policy if the decision is deliberately to avoid Serialize impls.

I haven't spent the time to think about it, but serde is a productive ecosystem to work with.  It would be a shame to lose compatibility with that ecosystem.  I wonder if there is a way to leverage serde but in an explicit way...

**Comment by tarcieri** [comment]
> One part I've struggled with here is the need to persist keys to another storage medium.

Pretty much all of the secret key types impl [`pkcs8::EncodePrivateKey`](https://docs.rs/pkcs8/latest/pkcs8/trait.EncodePrivateKey.html) which is a purpose-dedicated crate for private key serialization which can also handle things like persisting it to disk with appropriate file permissions as well as encrypting it under a passphrase.
