### ISSUE TITLE
slh-dsa: update to FIPS 205 final

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/signatures#843]
It's out: https://nvlpubs.nist.gov/nistpubs/fips/nist.fips.205.pdf

cc @tjade273

> ### A.1 Changes From FIPS 205 Initial Public Draft
> The differences from Version 3 of the SPHINCS+ specification described in Appendix A were
> included in the draft version of this standard (FIPS 205 ipd) that was posted on August 24, 2023.
> Based on comments that were submitted on FIPS 205 ipd, the SLH-DSA signature generation and
> verification functions were modified to include domain separation cases in which the message
> is signed directly and in which a digest of the message is signed. The changes were made by
> modifying the inputs to the signing and verification functions (see Algorithms 22, 23, 24, and 25).

**Comment by DiscordJim** [comment]
Anyone currently working on this? Would be thrilled to help out.

**Comment by tarcieri** [comment]
@DiscordJim might wait a day to hear from @tjade273, otherwise go for it

**Comment by DiscordJim** [comment]
@tarcieri Sounds good. Ideally I'd like to work on the 204 implementation first. Do you guys have a Discord or something of the like?

**Comment by tarcieri** [comment]
@DiscordJim you can find some discussion about implementing ML-DSA in #8. There's currently an empty `ml-dsa` crate in-tree. Ideally it would share some code with [`ml-kem`](https://github.com/RustCrypto/KEMs/tree/master/ml-kem). You can [chat about it on our Zulip](https://rustcrypto.zulipchat.com/#narrow/stream/260048-signatures)

**Comment by tjade273** [comment]
Nice! I can take care of this tomorrow morning

**Comment by tarcieri** [comment]
Fixed in #844
