### ISSUE TITLE
Unexpected slowdown of `try_sign_prehashed_rfc6979()` for some curve implementations

### ISSUE THREAD

**Issue by fjarri** [RustCrypto/signatures#880]
When `rfc6979::generate_k()` is called from `try_sign_prehashed_rfc6979()` in `ecdsa` crate, it's only given the length of the `Repr` of the field element. So when it does rejection sampling by repeatedly constructing a random `Repr` and comparing it to the modulus, it becomes unnecessarily slow if the number of bits in `Repr` is different from `PrimeField::NUM_BITS` for the field element. If it's significantly different, the execution essentially halts. But even if `Repr` bits and `PrimeField::NUM_BITS` are within one byte, there can still be an up to 128x unnecessary slowdown.

Should `generate_k()` somehow be made informed of `PrimeField::NUM_BITS`, so that it could apply a corresponding mask to the generated randoms?

**Comment by tarcieri** [comment]
Sure, an explicit bit length parameter sounds good.

Can you submit a pathological test case for this condition?

**Comment by fjarri** [comment]
Actually, my bad, it was fixed in #781. I guess I'll have to wait for `ecdsa` 0.17 to make use of it.
